version: '3.7'

services:
    sw-project-radar:
        build:
            context: .
            dockerfile: Dockerfile_node
        container_name: sw-radar-node
        restart: always
        init: true
        ports:
            - 8081:8080
        networks:
            sw-radar-nw:
        depends_on:
            - mongo
        volumes:
            - $PWD:/home/node/swforum-radar

    mongo:
        image: mongo:latest
        container_name: sw-radar-mongo
        restart: always
        volumes:
            - dbdata:/data/db
        ports:
            - 20017:27017
        networks:
            sw-radar-nw:

volumes:
    dbdata:
        name: sw-radar-data

networks:
    sw-radar-nw:
        name: sw-radar
