FROM node:16

# Create app directory
WORKDIR /home/node/swforum-radar

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied

COPY package*.json ./

RUN npm install


# Bundle app source
COPY . .

EXPOSE 8080

CMD [ "node", "src/server/server.js" ]
